apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: platform-dev
  namespace: argocd

spec:
  description: Development applications managed by the internal developer platform

  sourceRepos:
    - https://github.com/rahatdevops/idp-lab-gitops.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: demo

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
