apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: nginx
  description: NGINX application deployed through Argo CD and Helm

  annotations:
    backstage.io/kubernetes-id: nginx
    backstage.io/techdocs-ref: value

  tags:
    - nginx
    - kubernetes
    - gitops
    - helm
    - argocd

spec:
  type: service
  lifecycle: experimental
  owner: platform-team
